Feature/tms lesson 20
UladzimirKovel/MyHomework pull request #4
Opened 2024-11-18 10:38 UTC by UladzimirKovel

2024-12-04 15:44 UTC, EvgenKolesnik requested changes
Необходимо исправить замечания и заново запросить ревью

2024-12-04 15:44 UTC, EvgenKolesnik commented on app/src/main/java/com/example/myhomework/ListViewAuto.kt
> +    private lateinit var autoAdapter: AutoAdapter
Лучше избавиться от lateinit

2024-12-04 15:44 UTC, EvgenKolesnik commented on app/src/main/java/com/example/myhomework/ListViewAuto.kt
> +            startActivity(
стоит вынести логику из onCreate, разбить по функциям

2024-12-04 15:44 UTC, EvgenKolesnik commented on app/src/main/java/com/example/myhomework/LoginActivity.kt
>              }
конструкцию if лучше заменить на when

2024-12-04 15:44 UTC, EvgenKolesnik commented on app/src/main/java/com/example/myhomework/SignUpActivity.kt
>              }
if стоит заменить на when

2024-12-04 15:44 UTC, EvgenKolesnik commented on app/src/main/java/com/example/myhomework/ui/theme/adapter/AutoAdapter.kt
> +                }
в адаптере стоит держать логику только необходимую для работы адаптера, все что с ним не связано - вынести наружу. здесь стоит вынести обработку нажатия

2024-12-04 15:44 UTC, EvgenKolesnik commented on app/src/main/java/com/example/myhomework/ui/theme/adapter/AutoAdapter.kt
> +    }
аналогично

2024-12-04 15:44 UTC, EvgenKolesnik commented on app/src/main/java/com/example/myhomework/ui/theme/adapter/AutoAdapter.kt
> +            }
также

2024-12-04 15:44 UTC, EvgenKolesnik commented on app/src/main/res/layout/activity_login.xml
> +        android:textStyle="bold" />
вынести размеры в xml

2024-12-06 17:40 UTC, UladzimirKovel commented on app/src/main/java/com/example/myhomework/ui/theme/adapter/AutoAdapter.kt
> +                }
я переделал, но твой комментарий в студии почему-то пропал

2024-12-09 15:09 UTC, EvgenKolesnik commented
У тебя появились конфликты, разреши их и можно вливать

2024-12-09 15:09 UTC, EvgenKolesnik approved these changes

2024-12-10 09:24 UTC, merged